[package]
name = "dataflow-jit"
version = "0.1.0"
edition = "2021"

[dependencies]
bitvec = "1.0.1"
bitflags = "1.3.2"
cranelift = "0.90.1"
enum_dispatch = "0.3.8"
target-lexicon = "0.12.5"
dbsp = { path = "../../" }

    [dependencies.derive_more]
    version = "0.99.17"
    default-features = false
    features = ["from"]
