[package]
name = "dataflow-jit"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.9"
bitvec = "1.0.1"
size-of = "0.1.4"
bitflags = "1.3.2"
cranelift = "0.92.0"
enum_dispatch = "0.3.8"
cranelift-jit = "0.92.0"
target-lexicon = "0.12.5"
dbsp = { path = "../../" }
cranelift-module = "0.92.0"
cranelift-native = "0.92.0"
petgraph = { version = "0.6.2", features = ["graphmap"] }

    [dependencies.derive_more]
    version = "0.99.17"
    default-features = false
    features = ["from", "is_variant", "unwrap"]

    [dependencies.tinyvec]
    version = "1.6.0"
    features = ["std", "rustc_1_57"]

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
