[package]
name = "dataflow-jit"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0.9"
bitvec = "1.0.1"
size-of = "0.1.4"
bitflags = "1.3.2"
cranelift = "0.91.0"
enum_dispatch = "0.3.8"
cranelift-jit = "0.91.0"
target-lexicon = "0.12.5"
dbsp = { path = "../../" }
cranelift-module = "0.91.0"
cranelift-native = "0.91.0"

    [dependencies.derive_more]
    version = "0.99.17"
    default-features = false
    features = ["from"]
