inputs:
  Messages:
    stream: MESSAGES # messages table in our schema
    transport:
      name: file
      config: 
        path: "/examples/messages.csv"
        follow: true

    format:
      name: csv
          
  Records:
    stream: RECORDS # records table in our schema
    transport:
      name: file
      config: 
        path: "/examples/records.csv"
        follow: true

    format:
      name: csv

outputs:
  Filtered:
    stream: MESSAGE_COMBINER
    transport:
      name: file
      config: 
        path: "/examples/matches.csv"

    format:
      name: csv
