[package]
name = "dbsp_pipeline_manager"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
dbsp_adapters = { path = "../adapters" }
actix-web = "4.3"
actix-web-static-files = "4.0.0"
awc = "3.1.0"
static-files = "0.2.3"
actix-files = "0.6.2"
actix-cors = "0.6.4"
anyhow = { version = "1.0.57", features = ["backtrace"] }
tokio = { version = "1.25.0", features = ["fs", "macros", "process", "io-util", "io-std"] }
log = "0.4.17"
env_logger = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.89"
serde_yaml = "0.9.14"
mime = "0.3.16"
clap = { version = "4.0.32", features = ["derive"] }
regex = "1.7.0"
reqwest = "0.11.14"
fs_extra = "1.3.0"
utoipa = { version = "=3.0.3", features = ["actix_extras", "chrono"] }
utoipa-gen = { version = "=3.0.3" }
utoipa-swagger-ui = { version = "3.0.2", features = ["actix-web"] }
chrono = { version = "0.4.23", default-features = false, features = ["serde"] }
tempfile = { version = "3" }
actix = "0.13.0"
actix-web-actors = "4.2.0"
futures-util = "0.3.28"
futures = "0.3"
tokio-postgres = "0.7"
async-trait = "0.1"
# Waiting for https://github.com/faokunega/pg-embed/pull/26
pg-embed = { git = "https://github.com/gz/pg-embed.git", rev = "8906af8", optional = true }
once_cell = { version = "1.17.1", optional = true }

[target.'cfg(unix)'.dependencies]
daemonize = { version = "0.4.1" }

[build-dependencies]
static-files = "0.2.3"

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
pretty_assertions = "1.3.0"


[features]
default = ["dev"]
dev = ["dep:pg-embed", "dep:once_cell"]