[tasks.openapi_json]
description = "Dump OpenAPI specification of the REST API to 'openapi.json'"
dependencies = ["build-release"]
script = '''
cd ../../
cargo run --release --bin=dbsp_pipeline_manager -- --dump-openapi
'''

[tasks.openapi_python]
description = "Generate Python bindings for the REST API"
dependencies = ["openapi_json"]
script = '''
pip3 install openapi-python-client
cd ../../python
rm -rf dbsp-api-client
openapi-python-client generate --path ../openapi.json
pip3 install ./dbsp-api-client
pip3 install .
pip3 install websockets
'''

[tasks.start_manager]
script = '''
../../scripts/start_manager.sh
'''

[tasks.python_api_test]
description = "Test Python API"
dependencies = ["openapi_python", "start_manager"]
script = '''
python3 ../../python/test.py
'''

[tasks.fraud_notebook_test]
description = "Fraud detection Python notebook test"
dependencies = ["openapi_python", "start_manager"]
script = '''
cd ../../demo/demo_notebooks
pip3 install -r requirements.txt
IN_CI=1 jupyter execute fraud_detection.ipynb --JupyterApp.log_level='DEBUG'
'''

[tasks.python_test]
dependencies = ["fraud_notebook_test", "python_api_test"]

[tasks.test]
dependencies = ["python_test"]
