[package]
name = "dbsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = { version = "0.4.0" }
string-builder = { version = "0.2.0 "}
petgraph = { version = "0.6.0" }
