[package]
name = "dbsp"
version = "0.1.0"
edition = "2021"

[features]

default = ["with-serde"]
with-serde = ["serde"]

[dependencies]
num = "0.4.0"
string-builder = "0.2.0 "
petgraph = "0.6.0"
typedmap = { version = "0.2.0", features = ["dashmap"] }
crossbeam-utils = "0.8.6"
once_cell = "1.9.0"
priority-queue = "1.2.1"
hashbrown = "0.12.0"
csv = "1.1"
serde = { version = "1.0", optional = true }
