[workspace]
members = ["crates/*"]
exclude = ["sql-to-dbsp-compiler/temp"]

[profile.bench]
debug = true

# Waiting for bincode 2.0.0 to be released (https://github.com/thomcc/arcstr/pull/45)
[patch.crates-io.arcstr]
git = "https://github.com/gz/arcstr.git"
rev = "b43120c"
optional = true
