[package]
name = "dbsp"
version = "0.1.0"
edition = "2021"

[features]
default = ["with-serde"]
with-serde = ["serde"]
with-csv = ["csv"]
with-nexmark = [
    "arcstr",
    "cached",
    "clap",
    "csv",
    "rand",
    "regex",
    "rust_decimal",
    "time",
    "size-of/rust_decimal",
    "size-of/arcstr",
    "paste",
]

[dependencies]
num = "0.4.0"
anyhow = "1.0.57"
size-of = "0.1.1"
petgraph = "0.6.0"
typedmap = { version = "0.3.0", features = ["dashmap"] }
crossbeam-utils = "0.8.6"
once_cell = "1.9.0"
priority-queue = "1.2.1"
hashbrown = "0.12.0"
csv = { version = "1.1", optional = true }
serde = { version = "1.0", optional = true }
impl-trait-for-tuples = "0.2"
textwrap = "0.15.0"
fxhash = "0.2"
ordered-float = "3.0.0"
arcstr = { version = "1.1.4", optional = true }
rust_decimal = { version = "1.26.1", optional = true }
regex = { version = "1.6.0", optional = true }
time = { version = "0.3.14", features = ["formatting"], optional = true }
paste = { version = "1.0.9", optional = true }
bitvec = "1.0.1"

# TODO: Remove these dependencies
rand = { version = "0.8", optional = true }
clap = { version = "3.2", optional = true, features = ["derive", "env"] }
cached = { version = "0.38.0", optional = true }
crossbeam = "0.8.2"

[dev-dependencies]
zip = "0.6.2"
tar = "0.4.38"
rand = "0.8.5"
zstd = "0.10.0"
anyhow = "1.0.57"
rstest = "0.15"
cached = "0.38.0"
proptest = "1.0.0"
criterion = "0.3.6"
rand_xoshiro = "0.6.0"
indicatif = "0.17.0-rc.11"
mimalloc-rust-sys = "1.7.2"
clap = { version = "3.2.8", features = ["derive", "env"] }
reqwest = { version = "0.11.11", features = ["blocking"] }
ascii_table = "4.0.2"
num-format = "0.4.0"

[target.'cfg(unix)'.dev-dependencies]
libc = "0.2.127"

[profile.bench]
debug = true

[[bench]]
name = "galen"
harness = false
required-features = ["with-csv"]

[[bench]]
name = "path"
harness = false

[[bench]]
name = "nexmark"
harness = false
required-features = ["with-nexmark"]

[[bench]]
name = "consolidation"
harness = false

[[bench]]
name = "ldbc-graphalytics"
harness = false

[[bench]]
name = "column_leaf"
harness = false
