[package]
name = "dbsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
string-builder = "0.2.0 "
petgraph = "0.6.0"
typedmap = { version = "0.2.0", features = ["dashmap"] }
crossbeam-utils = "0.8.6"
once_cell = "1.9.0"
