{
 "title": "DBSP",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "pipeline_id", "query": { "query": "label_values(pipeline_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Input rate (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(input_total_bytes{pipeline_id=\"$pipeline_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input rate (records)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(input_total_records{pipeline_id=\"$pipeline_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output rate (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(output_transmitted_bytes{pipeline_id=\"$pipeline_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output rate (records)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by(endpoint) (rate(output_transmitted_records{pipeline_id=\"$pipeline_id\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}