services:
  web:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    ports:
      - "8001:8000"
    container_name: dbsp
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    ports:
      - "3000:3000"
      - "8081:8081"
      - "8082:8082"
      - "9092:9092"
      - "9644:9644"