on:
  push:
  release:
      types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/dbspmanager

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install jq tool
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Build Docker image
        run: |
          cd deploy && \
          docker build -f Dockerfile -t dbspmanager ../ && \
          docker build -f Dockerfile --target=client -t dbspmanager-dev ../

      - name: Run integration tests
        run: |
          cd deploy && \
          bash integration-tests.sh

      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          skipClusterCreation: "true"

      - name: Set up kind
        run: cd deploy/kind && ./setup.sh && ./setup.sh 
        
      # - name: Deploy DBSP
      #   run: cd deploy/kind && sleep 60 && kubectl apply -f dbsp-deploy.yml && kubectl wait --for=condition=ready pod -l app=dbsp -n dbsp --timeout=300s
      
      - name: Log in to the Container registry
        if: github.event_name == 'release'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        if: github.event_name == 'release'
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push Docker image
        if: github.event_name == 'release'
        run: |
          docker tag dbspmanager ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} && \
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
