
on:
  push:
  release:
      types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dbsp-demo/dbspmanager

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build Docker image
        run: |
          cd deploy && \
          docker build -f Dockerfile -t dbspmanager ../

      - name: Run integration tests
        run: |
          docker network create test && \
          docker run --name dbsp -h dbsp --network test -p 8080 -itd dbspmanager && \
          sleep 10 && \
          docker run --name test --network test --rm dbspmanager bash -c "/database-stream-processor/deploy/integration-tests.sh dbsp:8080"

      - name: Log in to the Container registry
        if: github.event_name == 'release'
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        if: github.event_name == 'release'
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push Docker image
        if: github.event_name == 'release'
        run: |
          docker tag dbspmanager ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} && \
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
