name: Coverage

on: [push, pull_request]

env:
  # It's really `--all-features`, but not adding `persistence`, we expect the
  # persistence feature to go away again in the future (but if we add it
  # unconditionally it changes the code that's run significantly)
  ALMOST_ALL_FEATURES: --features "with-serde with-csv with-nexmark"

jobs:
  check:
    name: Coverage
    runs-on: [self-hosted, Linux, skylake-2x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: llvm-tools-preview
          override: true

      - name: Restore cache
        uses: Swatinem/rust-cache@v1

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: ${{ env.ALMOST_ALL_FEATURES }} --workspace --lcov --output-path coverage.info --ignore-filename-regex tests.rs

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.info
          fail_ci_if_error: true

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: coverage.info
